// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_qHPFrxCzVxBdfOCf9soVOmMN0M4lHK8',
    appId: '1:818829356687:web:d59ddca0aa3ba8500a4afa',
    messagingSenderId: '818829356687',
    projectId: 'project-6efa2',
    authDomain: 'project-6efa2.firebaseapp.com',
    storageBucket: 'project-6efa2.firebasestorage.app',
    measurementId: 'G-S8L4V9ZFBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnQRjoA0toYWNwuYKSQZOXz6WqAPZOug',
    appId: '1:818829356687:android:9f71be908c816ffb0a4afa',
    messagingSenderId: '818829356687',
    projectId: 'project-6efa2',
    storageBucket: 'project-6efa2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_qHPFrxCzVxBdfOCf9soVOmMN0M4lHK8',
    appId: '1:818829356687:web:d8d8aeb5b680cd610a4afa',
    messagingSenderId: '818829356687',
    projectId: 'project-6efa2',
    authDomain: 'project-6efa2.firebaseapp.com',
    storageBucket: 'project-6efa2.firebasestorage.app',
    measurementId: 'G-JST4JF6TK2',
  );
}
